apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: local-storage-operator-serving-cert
  name: local-storage-operator-metrics
  namespace: openshift-local-storage
  labels:
    app: local-storage-operator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: metrics
  selector:
    app: local-storage-operator
